# -*- coding: utf-8 -*-
"""M22RM002_Q8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ja9oIdmV9P-kYmE7wN_iVsqeXv7oLRt
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow 

img = cv2.imread("name.jpg")
img1 = cv2.imread("name.jpg")

grey_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("temp.jpg", 0)
w, h = template.shape[::-1]

res = cv2.matchTemplate(grey_img, template, cv2.TM_CCORR_NORMED)
threshold = 0.999
loc = np.where(res >= threshold)  

count = 0
for i in zip(*loc[::-1]):
   
    cv2.rectangle(img, i, (i[0] + w, i[1] + h), (0, 0, 255), 2)
    count+=1

img = cv2.resize(img,(800,600))
res = cv2.resize(res,(800,600))

template=cv2.resize(template,(300,400))
cv2_imshow(template)
cv2_imshow( img)

