# -*- coding: utf-8 -*-
"""M22RM002_Q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQS6IXmZLVwU3ALuo85ES9gsC-KJOs2F
"""

from IPython.core.display import Image
import cv2
import numpy as np

from google.colab.patches import cv2_imshow 


def finding_edges(img):
    gray_image= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    canny_image=cv2.Canny(gray_image,400,130,apertureSize=3)

    return canny_image


def finding_angle(canny_image,image):
    lined_image=cv2.HoughLinesP(canny_image,1,np.pi/180,49,minLineLength=10,maxLineGap=0)
    
    l=[]
    
    for i in range(4):
        l.append(lined_image[0][0][i])
    x1=l[0]
    x2=l[2]
    y1=l[1]
    y2=l[3]
    
    if x1==x2:
        m1=np.pi/2
    else:
         m1= np.arctan2((y2-y1),(x2-x1))
    
    l=[]
    for i in range(4):
        l.append(lined_image[2][0][i])
    x1=l[0]
    x2=l[2]
    y1=l[1]
    y2=l[3]
    
    if x1==x2:
        m2=np.pi/2
    else:
        m2= np.arctan2((y2-y1),(x2-x1))

    angle=m1-m2

    val = abs((angle * 180) / np.pi)
    val=round(val,3)
    print(f"The Angle between minute's and hour's hand is {val} degrees")
    
if __name__=="__main__":

    image=cv2.imread('clock_1.png')
    cv2_imshow(image)

    canny_image=finding_edges(image)

    finding_angle(canny_image,image)

