# -*- coding: utf-8 -*-
"""M22RM002_Q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u4eBcdewVMsOq79ItTJok_Vbyf6sIMNK
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import math
import os
import tensorflow as tf
import keras
import pandas as pd
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from tensorflow.keras.preprocessing import image

#mount google drive
from google.colab import drive
drive.mount('/content/drive')

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import math
import os
import tensorflow as tf
import keras
import pandas as pd
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from tensorflow.keras.preprocessing import image

from sklearn import metrics
from sklearn import svm

train_dataset=train.flow_from_directory('COMPUTER_VISION/ASSIGNMENT_1/Question_6/base_data/training/',
                                       target_size=(25,25),
                                       batch_size=5,
                                       class_mode='binary')
 
svm_linear = svm.SVC(kernel='linear')

svm_linear.fit(x_train, y_train)

predictions = svm_linear.predict(x_test)

metrics.accuracy_score(y_true=y_test, y_pred=predictions)

from sklearn.metrics import classification_report
predictions=model_linear.predict(X_test)
print(classification_report(y_test,predictions))