# -*- coding: utf-8 -*-
"""M22RM002_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b-FfFUCUwyiBmK0ROfNeBVfq0MreEqlM
"""

import numpy as np
import cv2 
import math
from google.colab.patches import cv2_imshow 

img = cv2.imread('circle-updated.png')
output = img.copy()
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.medianBlur(gray, 5)
circles = cv2.HoughCircles(gray, cv2.HOUGH_GRADIENT, 1,30,
                          param1=60, param2=110, minRadius=50, maxRadius=0)
detected_circles = np.uint16(np.around(circles))

for (x, y ,r) in detected_circles[0, :]:
    
    cv2.circle(output, (x, y), r, (255, 0, 0), 3)
    cv2.circle(output, (x, y), 2, (0, 0, 255), 3)
    area = math.pi*(r*r)
    area = round(area,3)
    perimeter=2*math.pi*r
    perimeter=round(perimeter,3)
    image = cv2.putText(output, 'Area:'+str(area), (170,300), cv2.FONT_HERSHEY_SIMPLEX, 
                   1, (255, 0, 0), 1, cv2.LINE_AA)
    image = cv2.putText(output, 'Perimeter:'+str(perimeter), (170,250), cv2.FONT_HERSHEY_SIMPLEX, 
                   1, (255, 0, 0), 1, cv2.LINE_AA)
print("Area:",area)
print("Perimeter:",perimeter)

cv2_imshow(image)

