# -*- coding: utf-8 -*-
"""M22RM002_Q10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ton4v9-ZOxdYqzYQ82kuHVeR7Il2Ag87
"""

!sudo apt-get install tesseract-ocr

!pip install pytesseract==0.3.9

import cv2

import pytesseract
from pytesseract import Output



def threshold_image(image):

  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
  threshold_img = cv2.threshold(gray_image, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]

  return threshold_img

def last__three_digits(threshold_img):

    i=0

    custom_config = r'--oem 3 --psm 6'

    details = pytesseract.image_to_data(threshold_img,output_type=Output.DICT, config=custom_config, lang='eng')

    for keys,value in details.items():
      if (i==11):
        print("Given phone number is :", value[4])
        print("Last three digits of given number is :",value[4][7:])
      i=i+1

if __name__=="__main__":

  image = cv2.imread("phone_num_2.png")
  
  cv2_imshow(image)

  threshold_img =threshold_image(image)

  last__three_digits(threshold_img)

