# -*- coding: utf-8 -*-
"""M22RM002_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XhysD8buZrnREtx0xmyIHUbl21Pa6JPn
"""

import numpy as np
import cv2
import imutils

from google.colab.patches import cv2_imshow 

img1=cv2.imread("Spot_the_difference.png",1)

img2 = img1[:, 0:350]

img3 = img1[:,350:700]

gray1=cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
gray2=cv2.cvtColor(img3,cv2.COLOR_BGR2GRAY)

diff=cv2.absdiff(gray1,gray2)


thresh=cv2.threshold(diff,0,255,cv2.THRESH_BINARY|cv2.THRESH_OTSU)[1]



kernel=np.ones((3,3),np.uint8)
dilate=cv2.dilate(thresh,kernel,iterations=2)


contuors=cv2.findContours(dilate.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
contuors=imutils.grab_contours(contuors)

for contour in contuors:
    if cv2.contourArea(contour)>100:
        x,y,w,h=cv2.boundingRect(contour)
        cv2.rectangle(img2,(x,y),(x+w,y+h),(0,0,255),2)
        cv2.rectangle(img3,(x,y),(x+w,y+h),(0,0,255),2)
        
cv2_imshow(img2)
cv2_imshow(img3)

"""# New Section"""