# -*- coding: utf-8 -*-
"""M22RM002_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1leVra7e9rX6ZH08256ro_F2oT0jaiRjy
"""

# Pip install (recommended)

!pip install ultralytics

## importing required libraries
import os
import shutil
import random

!pip install tqdm --upgrade
from tqdm.notebook import tqdm

## connecting to the google drive

from google.colab import drive
drive.mount('/content/drive')

import ultralytics
ultralytics.checks()

"""## Model Training"""

!yolo task=detect mode=train model=yolov8s.pt data=/content/drive/MyDrive/Colab_Notebooks/CV_ASSIGN_4/QUESTION_3/yolo/roboflow/data.yaml epochs=4 imgsz=640 batch=8 project=/content/drive/MyDrive/yolov8/training_results name=animal

"""## Prediction on Test Image"""

!yolo task=detect mode=predict model=/content/drive/MyDrive/yolov8/training_results/animal3/weights/best.pt conf=0.55 source=/content/drive/MyDrive/Colab_Notebooks/CV_ASSIGN_4/QUESTION_3/yolo/roboflow/test/images

!cp -r /content/runs/detect/predict /content/drive/MyDrive/Colab_Notebooks/CV_ASSIGN_4/QUESTION_3/yolo/output

"""## Plot of Results"""

import matplotlib.pyplot as plt
import numpy as np
import os

folder_path = '/content/drive/MyDrive/Colab_Notebooks/CV_ASSIGN_4/QUESTION_3/yolo/output/predict'

image_files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

images = []
for f in image_files:
    image_path = os.path.join(folder_path, f)
    image = plt.imread(image_path)
    images.append(image)

# Create a 3x3 grid of subplots
fig, axs = plt.subplots(nrows=3, ncols=3, figsize=(9, 9))

# Loop over the images and plot them in the subplots
for i in range(9):
    row = i // 3
    col = i % 3
    axs[row, col].imshow(images[i])
    axs[row, col].axis('off')

plt.show()

